config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get '/dashboard', to: 'dashboard#index'

  namespace :dashboard do
    get '/' => 'home#index'

    resources :orders
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'

  enum status: [:pending_payment, :partially_paid, :paid, :canceled, :refunded, :expired]
  validates_presence_of :status

  def self.search_by(search_params)
    orders = search_params[:user_email].present? ? includes(:user).where(users: { email: search_params[:user_email] }) : self
    orders = orders.where(status: search_params[:status]) if search_params[:status].present? && Order.statuses.keys.include?(search_params[:status])

    orders
  end

  def self.lock_data(user)
    user.update!(additional_info: { last_lock_order: Time.current })
    where("created_at <= ?", user.additional_info[:last_lock_order] || Time.current)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy

  validates_presence_of :email, :password
  serialize :additional_info
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate_admin!
    redirect_to dashboard_path, flash: { alert: "Sorry, you're not authorized to access this page." } unless current_user&.admin?
  end
end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < ApplicationController
  layout 'dashboard'

  before_action :authenticate_user!
  before_action :authenticate_admin!

  def index
    # lock orders for the issue duplicate item on next pages
    @orders = Order.all.lock_data(current_user).includes(:user)
    @orders = @orders.search_by(status: params[:status],  user_email: params[:user_email]) if params[:status] != 'status' || params[:user_email].present?
    @orders = @orders.page(params[:page] || 1).per(params[:per] || 10)
  end

  def edit
    @order = Order.find_by(id: params[:id])
  end

  def update
    @order = Order.find_by(id: params[:id])
    @order.update(order_params)

    render 'edit'
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'dashboard'
  before_action :authenticate_user!
  # before_action :authenticate_admin!

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if current_user.present?
      if current_user.admin?
        redirect_to dashboard_path
      else
        redirect_to dashboard_path, flash: { error: "Sorry, you're not authorized to access this page." }
      end
      # redirect_to(dashboard_path)
    else
      redirect_to new_user_session_path, flash: { error: "Please login." }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<!-- <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Home Work</a>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <%= link_to '#', class: 'nav-link' do %>
        <span><i class="fas fa-user"></i></span>
      <% end %>
    </li>
    <li class="nav-item text-nowrap">
      <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
        <span><i class="fas fa-sign-out-alt"></i></span>
      <% end %>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="#">
              <span><i class="fas fa-home"></i></span>
              Dashboard <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <%= link_to dashboard_orders_path, class: 'nav-link' do %>
              <span><i class="fas fa-shopping-cart"></i>
                Orders</span>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
    <main class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4 mainbar">
      <p>Welcome to dashboard</p>
      <nav class="navbar navbar-dark sticky-bottom bg-dark flex-md-nowrap p-0">
    </div>
  </div>
</div>
 -->

<p>Welcome to dashboard</p>

app/views/dashboard/orders/edit.html.erb
<h2>Edit order</h2>
<%= form_for([:dashboard, @order]) do |f| %>
  <%= render 'shared/error_messages' %>
  <p>
    <%= f.label :status %>
    <%= f.collection_select(:status, Order.statuses.keys, :to_s, :to_s, include_blank: false) %>
  </p>
  <p>
    <%= f.submit 'Save' %>
  </p>
<% end %>

app/views/dashboard/orders/index.html.erb
<div class="row">
  <div class="col-lg-12 card-margin">
    <h4>Search</h4>
    <div class="search-form">
      <div class="card-body p-0">
        <form id="search-form">
          <div class="row">
            <div class="col-12">
              <div class="row no-gutters">
                <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                  <%= select_tag "status", options_from_collection_for_select(Order.statuses.keys.unshift('status'), :to_s, :to_s, selected: params[:status], include_blank: true), class: 'form-control' %>
                </div>
                <div class="col-lg-8 col-md-6 col-sm-12 p-0">
                  <!-- <input type="text" placeholder="User email..." class="form-control" id="search" name="search"> -->
                  <%= text_field_tag :user_email, params[:user_email], placeholder: 'user@example.com', class: 'form-control' %>
                </div>
                <div class="col-lg-1 col-md-3 col-sm-12 p-0">
                  <button type="submit" class="btn btn-base">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<table class="table table-bordered">
  <thead class="thead">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Product Name</th>
      <th scope="col">User Email</th>
      <th scope="col">Status</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></th>
        <td><%= order.product_name %></td>
        <td><%= order.user.email %></td>
        <td><%= order.status %></td>
        <td>
          <%= link_to edit_dashboard_order_path(order) do %>
            <span><i class="fas fa-edit"></i></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @orders %>

app/views/layouts/_footer.html.erb
<p>My home work - 2021</p>

app/views/layouts/_header.html.erb
<a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Home Work</a>
<ul class="navbar-nav px-3">
  <li class="nav-item text-nowrap">
    <%= link_to '#', class: 'nav-link' do %>
      <span><i class="fas fa-user"></i></span>
    <% end %>
  </li>
  <li class="nav-item text-nowrap">
    <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
      <span><i class="fas fa-sign-out-alt"></i></span>
    <% end %>
  </li>
</ul>

app/views/layouts/_left_sidebar.html.erb
<div class="sidebar-sticky">
  <ul class="nav flex-column">
    <li class="<%= 'active' if params[:controller] == 'dashboard' %> nav-item">
      <%= link_to dashboard_path, class: "nav-link" do %>
        <span><i class="fas fa-home"></i>
          Dashboard</span>
      <% end %>
    </li>
    <li class="<%= 'active' if params[:controller] == 'dashboard/orders' %> nav-item">
      <%= link_to dashboard_orders_path, class: 'nav-link' do %>
        <span><i class="fas fa-shopping-cart"></i>
          Orders</span>
      <% end %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
  <head>
    <!-- <title>Homework</title> -->
    <title>Login Page</title>
    <!--Made with love by Mutiullah Samim -->

    <!--Bootsrap 4 CDN-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

      <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
  <head>
    <!-- <title>Homework</title> -->
    <title>Login Page</title>
    <!--Made with love by Mutiullah Samim -->

    <!--Bootsrap 4 CDN-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

      <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <%= render 'layouts/header' %>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <%= render 'layouts/left_sidebar' %>
        </nav>
        <main class="col-md-9 ml-sm-auto col-lg-10 pt-3 mainbar">
          <div class="px-4">
            <div class="align-items-center remember">
              <% if flash[:alert] %>
                <p class="alert alert-danger"><%= flash[:alert] %></p>
              <% end %>
            </div>
            <%= yield %>
          </div>

          <nav class="sticky-bottom bg-dark px-4 flex-md-nowrap p-0">
            <%= render 'layouts/footer' %>
          </nav>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
 <% if @order.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@order.errors.count, "error") %>.
    </div>
    <ul>
    <% @order.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>